"""baseline

Revision ID: 02eeb03e8bc1
Revises: 
Create Date: 2026-04-22 10:57:05.689130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02eeb03e8bc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # CITEXT is used by users.email for case-insensitive uniqueness.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_monthly_credits', sa.Integer(), nullable=False),
    sa.Column('credit_usd_value_micros', sa.Integer(), nullable=False),
    sa.Column('openai_budget_micros', sa.Integer(), nullable=False),
    sa.Column('perplexity_budget_micros', sa.Integer(), nullable=False),
    sa.Column('global_budget_micros', sa.Integer(), nullable=False),
    sa.Column('perplexity_degrade_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('hard_stop_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('pricing_openai_input_per_mtok_micros', sa.Integer(), nullable=False),
    sa.Column('pricing_openai_output_per_mtok_micros', sa.Integer(), nullable=False),
    sa.Column('pricing_perplexity_input_per_mtok_micros', sa.Integer(), nullable=False),
    sa.Column('pricing_perplexity_output_per_mtok_micros', sa.Integer(), nullable=False),
    sa.Column('pricing_perplexity_request_fee_micros', sa.Integer(), nullable=False),
    sa.Column('pricing_web_search_per_call_micros', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_budget_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('openai_spend_micros', sa.Integer(), nullable=False),
    sa.Column('perplexity_spend_micros', sa.Integer(), nullable=False),
    sa.Column('web_search_spend_micros', sa.Integer(), nullable=False),
    sa.Column('perplexity_degraded', sa.Boolean(), nullable=False),
    sa.Column('hard_stopped', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_state',
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('code_verifier', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('redirect_to', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_oauth_state_expires_at'), 'oauth_state', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mentee_sub', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_mentee_sub'), 'users', ['mentee_sub'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id_token_nonce', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_last_used_at'), 'sessions', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_user_id_updated_at', 'threads', ['user_id', 'updated_at'], unique=False)
    op.create_table('user_quota',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('credits_used_period', sa.Integer(), nullable=False),
    sa.Column('credits_granted_period', sa.Integer(), nullable=False),
    sa.Column('override_monthly_credits', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_thread_id_created_at', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('message_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd_micros', sa.Integer(), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_usage_user_id_created_at', 'message_usage', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema — baseline migration, so wipe everything cleanly."""
    op.execute("DROP SCHEMA public CASCADE")
    op.execute("CREATE SCHEMA public")
