"""drop_budget_caps_add_flag_reasons

Revision ID: 28f02d2be7c1
Revises: 02eeb03e8bc1
Create Date: 2026-04-23 11:51:01.237353

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28f02d2be7c1'
down_revision: str | Sequence[str] | None = '02eeb03e8bc1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_config', 'perplexity_budget_micros')
    op.drop_column('budget_config', 'openai_budget_micros')
    op.drop_column('budget_config', 'hard_stop_threshold_pct')
    op.drop_column('budget_config', 'perplexity_degrade_threshold_pct')
    op.drop_column('budget_config', 'global_budget_micros')
    op.add_column(
        'global_budget_state',
        sa.Column(
            'perplexity_degrade_reason',
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
    )
    op.add_column(
        'global_budget_state',
        sa.Column(
            'perplexity_degraded_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        'global_budget_state',
        sa.Column(
            'hard_stop_reason',
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
    )
    op.add_column(
        'global_budget_state',
        sa.Column(
            'hard_stopped_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('global_budget_state', 'hard_stopped_at')
    op.drop_column('global_budget_state', 'hard_stop_reason')
    op.drop_column('global_budget_state', 'perplexity_degraded_at')
    op.drop_column('global_budget_state', 'perplexity_degrade_reason')
    # Server defaults match the original SQLModel defaults so existing rows
    # back-fill cleanly; drop the default afterwards so the schema matches
    # the old baseline.
    op.add_column(
        'budget_config',
        sa.Column(
            'global_budget_micros',
            sa.INTEGER(),
            server_default=sa.text('50000000'),
            nullable=False,
        ),
    )
    op.add_column(
        'budget_config',
        sa.Column(
            'perplexity_degrade_threshold_pct',
            sa.INTEGER(),
            server_default=sa.text('90'),
            nullable=False,
        ),
    )
    op.add_column(
        'budget_config',
        sa.Column(
            'hard_stop_threshold_pct',
            sa.INTEGER(),
            server_default=sa.text('95'),
            nullable=False,
        ),
    )
    op.add_column(
        'budget_config',
        sa.Column(
            'openai_budget_micros',
            sa.INTEGER(),
            server_default=sa.text('30000000'),
            nullable=False,
        ),
    )
    op.add_column(
        'budget_config',
        sa.Column(
            'perplexity_budget_micros',
            sa.INTEGER(),
            server_default=sa.text('20000000'),
            nullable=False,
        ),
    )
    for col in (
        'global_budget_micros',
        'perplexity_degrade_threshold_pct',
        'hard_stop_threshold_pct',
        'openai_budget_micros',
        'perplexity_budget_micros',
    ):
        op.alter_column('budget_config', col, server_default=None)
