"""add bug_reports and credit_requests

Revision ID: 33a29e77fa4e
Revises: 4f1a8b2d9c30
Create Date: 2026-04-29 13:12:38.865455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33a29e77fa4e'
down_revision: Union[str, Sequence[str], None] = '4f1a8b2d9c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('resolved_by_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_reports_status_created_at', 'bug_reports', ['status', 'created_at'], unique=False)
    op.create_index('ix_bug_reports_user_id', 'bug_reports', ['user_id'], unique=False)
    op.create_table('credit_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('granted_amount', sa.Integer(), nullable=True),
    sa.Column('granted_by_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_requests_status_created_at', 'credit_requests', ['status', 'created_at'], unique=False)
    op.create_index('ix_credit_requests_user_id', 'credit_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_requests_user_id', table_name='credit_requests')
    op.drop_index('ix_credit_requests_status_created_at', table_name='credit_requests')
    op.drop_table('credit_requests')
    op.drop_index('ix_bug_reports_user_id', table_name='bug_reports')
    op.drop_index('ix_bug_reports_status_created_at', table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
