"""initial schema

Revision ID: 3c0d1eb294a4
Revises: 
Create Date: 2026-04-18 14:34:23.122938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c0d1eb294a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_state',
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('code_verifier', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('redirect_to', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_oauth_state_expires_at'), 'oauth_state', ['expires_at'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('mentee_sub', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id_token_nonce', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_mentee_sub'), 'sessions', ['mentee_sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_mentee_sub'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_oauth_state_expires_at'), table_name='oauth_state')
    op.drop_table('oauth_state')
    # ### end Alembic commands ###
