"""add_budget_config_change_log

Revision ID: a95d27470bc2
Revises: 28f02d2be7c1
Create Date: 2026-04-23 12:10:29.864210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95d27470bc2'
down_revision: Union[str, Sequence[str], None] = '28f02d2be7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_config_change_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=True),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_config_change_log_changed_at', 'budget_config_change_log', ['changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_config_change_log_changed_at', table_name='budget_config_change_log')
    op.drop_table('budget_config_change_log')
    # ### end Alembic commands ###
