/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminActivityIndexRouteImport } from './routes/admin.activity.index'
import { Route as AdminActivityThreadIdRouteImport } from './routes/admin.activity.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityIndexRoute = AdminActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminActivityRoute,
} as any)
const AdminActivityThreadIdRoute = AdminActivityThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AdminActivityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/admin/activity': typeof AdminActivityRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/activity/$threadId': typeof AdminActivityThreadIdRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin': typeof AdminIndexRoute
  '/admin/activity/$threadId': typeof AdminActivityThreadIdRoute
  '/admin/activity': typeof AdminActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/admin/activity': typeof AdminActivityRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/activity/$threadId': typeof AdminActivityThreadIdRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/admin/activity'
    | '/admin/users'
    | '/auth/error'
    | '/admin/'
    | '/admin/activity/$threadId'
    | '/admin/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/admin/users'
    | '/auth/error'
    | '/admin'
    | '/admin/activity/$threadId'
    | '/admin/activity'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/admin/activity'
    | '/admin/users'
    | '/auth/error'
    | '/admin/'
    | '/admin/activity/$threadId'
    | '/admin/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChatRoute: typeof ChatRoute
  AuthErrorRoute: typeof AuthErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity/': {
      id: '/admin/activity/'
      path: '/'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AdminActivityIndexRouteImport
      parentRoute: typeof AdminActivityRoute
    }
    '/admin/activity/$threadId': {
      id: '/admin/activity/$threadId'
      path: '/$threadId'
      fullPath: '/admin/activity/$threadId'
      preLoaderRoute: typeof AdminActivityThreadIdRouteImport
      parentRoute: typeof AdminActivityRoute
    }
  }
}

interface AdminActivityRouteChildren {
  AdminActivityThreadIdRoute: typeof AdminActivityThreadIdRoute
  AdminActivityIndexRoute: typeof AdminActivityIndexRoute
}

const AdminActivityRouteChildren: AdminActivityRouteChildren = {
  AdminActivityThreadIdRoute: AdminActivityThreadIdRoute,
  AdminActivityIndexRoute: AdminActivityIndexRoute,
}

const AdminActivityRouteWithChildren = AdminActivityRoute._addFileChildren(
  AdminActivityRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChatRoute: ChatRoute,
  AuthErrorRoute: AuthErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
